name: asteroidsofgalaxysio2109
version: 0.0.1
author: Jean-François Gagnon
description: Projet de fin de session dans le cadre du cours SIO-2109 à l'Université Laval. Automne 2014. Adapté du jeu Invaders de Timur Ridjanovic.
homepage: https://github.com/jeffgagnon01
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.11.0'
  stopwatch: 0.15.1
